### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by doggy-dev** [kassenaerztliche-bundesvereinigung/MIOViewer#2]
The examples that can be downloaded from https://mio.kbv.de/display/MIOATT/MIO+Viewer cannot be opened in the mio viewer.

**Comment by mioviewer** [comment]
Hello,

thank you for your interest in our software. 
Can you provide a link to the concrete example that you used? The link does not lead to any examples. 

Please note that you need to use the right versions.
The changelog provides that information: https://github.com/kassenaerztliche-bundesvereinigung/MIOViewer/blob/master/CHANGELOG.md
