### ISSUE TITLE
Patient-Card, Anamnese - Validation message missing?

### ISSUE THREAD

**Issue by Mohammed-kharbotli** [kassenaerztliche-bundesvereinigung/MIOViewer#3]
Hallo,
i had the following Problem:

i created a "Mutterpass" XML-File,

MIO Viewer was able to open the XML **BUT!**
- in MIO Viewer the patient card section was not displayed
- when i dlicked on Anamnese under "Anamnese und allgemeine Befunde" MIO viewer crashed

after long Debugging i found the Problem, which is:
in the Patient-entry in Address Section missed the country.

`<address>`
`....`
 `
<country value="D"/>
`
`....`
`</address>`

is it possible that the MIO Viewer delivers Validation messages  for this case and other possible cases?

**Comment by mioviewer** [comment]
Hello,

thank you for reaching out to us. I was able to reproduce the issue. It seems that the validation isn't working since country has the cardinality of 1..1.
We will look into this issue and provide a fix in the future.

**Comment by mioviewer** [comment]
We found the issue and will fix it in the next release.
